spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update