spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
auth:
  service:
    environment: ${ENVIRONMENT_URL:http://localhost:3000}
    register: ${REGISTER_URL:/auth/register}
    login: ${LOGIN_URL:/auth/login}
    home: ${HOME_URL:/home}